GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Go to the gym"
}

###

DELETE http://localhost:3001/todo/delete/64ecf6bc1c25a0bd09ea5724

###

PUT http://localhost:3001/todo/complete/64ecf6c11c25a0bd09ea5728